name: CI

on:
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Hello, world!


      - name: Prepare git
        env:
          GITHUB_USER: 1gtm
          # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.LGTM_GITHUB_TOKEN }}
        run: |
          echo $GITHUB_SERVER_URL
          git config user.name "${GITHUB_USER}"
          git config user.email "${GITHUB_USER}@appscode.com"
          git remote set-url origin "https://${GITHUB_USER}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
          git remote -v

      - name: Update charts
        run: |
          ./hack/scripts/trigger.sh
